### ISSUE TITLE
{:error, %Pillar.HttpClient.TransportError{reason: :socket_closed_remotely}}

### ISSUE THREAD

**Issue by Dvogiatz** [balance-platform/pillar#22]
I'm currently getting this error:
```elixir
{:error, %Pillar.HttpClient.TransportError{reason: :socket_closed_remotely}}
```
I believe the issue is with `httpc.request` and after looking around to similar issues I've found these 2 topics, that could possibly be relevant.

[issue with default httpc adapter](https://github.com/teamon/tesla/issues/242#issuecomment-418827075)
[issue with default profile in httpc](https://github.com/phoenixframework/phoenix/issues/1478#issuecomment-173195841)

**Comment by sofakingworld** [comment]
@Dvogiatz Hi!

could you provide please more information?

- sql request
- pillar version
- clickhouse version
- function call example

**Comment by Dvogiatz** [comment]
@sofakingworld Hello, thank you for the quick response. 

I do a bulk insert of 1000 rows to a table, using a custom poolboy transaction with cast 
```elixir
:poolboy.transaction(
      String.to_atom(customer),
      fn pid ->
        GenServer.cast(
          pid,
          {:insert_to_table, table, items, %{}}
        )
      end,
      @pool_timeout_for_waiting_worker
    )
```
The reason I don't use the `use Pillar` method for ClickHouse master is because I have multiple databases and wanted to support the connection dynamically every time. 

Pillar version is the latest, 

Clickhouse version is `yandex/clickhouse-server:20.6.3.28`,

I have a similar insert_to_table function that I call with a list of maps(items) which inside calls the pooboy transaction. 

I couldn't replicate the issue locally on a single node. On production cluster I have 2 shards (using zookeeper). So the insert is writing to a random one each time.

**Comment by sofakingworld** [comment]
What about a temporary downgrade? 

https://hex.pm/packages/pillar/0.19.0 (uses Tesla with Mint, instead of httpc) 

If this version work great for you, we return Tesla and avoid httpc in next releases.

**Comment by Dvogiatz** [comment]
@sofakingworld Sure, I will try this and will let you know. thanks

**Comment by Dvogiatz** [comment]
@sofakingworld We seem to be error-free for the last 2 days using 0.19.0. Before downgrading I was getting the error almost once per hour depending on the data traffic, so Tesla with Mint seems to be working better on shards

**Comment by sofakingworld** [comment]
@Dvogiatz thanks! Will fix in new release
