### ISSUE TITLE
Type conversion for IPv4/IPv6

### ISSUE THREAD

**Issue by ifoo** [balance-platform/pillar#30]
At the moment, selecting `IPv4` or `IPv6` columns from CH fails in `Pillar.TypeConvert.ToElixir.convert/2`, since those two types are not checked. I'd be happy to send a PR, but I'd like to get an agreement, on what Elixir data type should be returned.

We could either return it as Erlang's `:inet.ip_address()` type (see https://www.erlang.org/doc/man/inet.html#type-ip_address ) or just as plain string.

What do you think?

**Comment by sofakingworld** [comment]
@ifoo hello!

I will be happy to accept a PR :)

I think the plain string is a bad solution, because of parse troubles and possible mistakes of data type select

> We could either return it as Erlang's :inet.ip_address()

seems good

{:inet4, {127.0.0.1}} - ToClickhouse -> "127.0.0.1"
"127.0.0.1" - FromClickhouse -> {:inet4, {127.0.0.1}}

And same for IPv6, {:inet6, {...,...,....}}
https://www.erlang.org/doc/man/inet.html#type-ip6_address

Do you agree and what do you think about this?

**Comment by ifoo** [comment]
Hi @sofakingworld,

since Pillar is using JSON/JSONEachRow as transport format, Clickhouse expect's (and returns) the IPs as string anyway.

Unfortunately, there seems to be some "inconsistencies" in the current version of CH. Inserting a string based IPv4 into a `IPv4` type column works. On IPv6 side, inserting as string works as well (at least for IPv6 strings). Except for INSERT SELECT (see https://github.com/ClickHouse/ClickHouse/issues/20098). I would expect that a IPv4 string inserted into a IPv6 field should also work (since it does for toIPv6(...), see https://github.com/ClickHouse/ClickHouse/issues/18152), but it doesn't, unless the string is an ipv4-mapped-ipv6 address already. I didn't find a bug report on CH's github for this yet.

Apart from this issues, i'm wondering if there is much value in converting to Erlang's `ip_address` types? I think they are not a very prominent type and i'd expect that people might not wan't to manually convert IPs back to strings for using them (e.g. rendering on website), but i'm not sure about this.

If going with `ip_address` type is the way forward, I would also suggest to not use the `{:inet4 | :inet6}` tuple prefix, since it's not adding any value (imho). IPv4 and IPv6 types are distinguishable by their length. Even in Erlang (`:inet` mostly) they only use the IP tuples directly without any "prefix".

I think the technical issues can be handled, so ultimately, it's a matter or preference I guess. Using `ip_address` types feels more "strict and correct", using strings feels more "user friendly".

**Comment by sofakingworld** [comment]
@ifoo Thanks for patience and explanation 👍🏻

Before your comment, I thought, that Clickhouse can't convert string to IP automatically, that's why I preferred the option with :inet tuple

Now I see that clickhouse can convert strings (with some workarounds) and now agree with you, lets use strings

**Comment by ifoo** [comment]
OK, I will try to submit a PR in the next days, based on `strings`. For good measure, I'll try to include automatic conversion for `ip_address()` types in `ToClickhouse` as well.

**Comment by sofakingworld** [comment]
@ifoo Thanks for the help and improvements!
