### ISSUE TITLE
how to use runtime config with pool of workers?

### ISSUE THREAD

**Issue by antonovga** [balance-platform/pillar#47]
Hi, can you provide an example how to use pool of workers with runtime config, to hide connection strings in env variables?

```
defmodule ClickhouseMaster do
  use Pillar,
    connection_strings: [
      "http://user:password@host-master-1:8123/database",
      "http://user:password@host-master-2:8123/database"
    ],
    name: __MODULE__,
    pool_size: 15
end

ClickhouseMaster.start_link()
```

in this scenario variables are being read while compilation time, if we try to pass Application.fetch_env or similar, in Application children = [...] I get a compile time error

**Comment by sofakingworld** [comment]
@antonovga Hi!

```
defmodule MyApp.Clickhouse.Pool do
  @moduledoc false

  use Pillar,
    connection_strings: connections_list(),
    name: __MODULE__,
    pool_size: 80

  def connections_list do
    urls = Application.fetch_env!(:my_app, MyApp.Clickhouse)[:connection_urls]
    String.split(urls, ",")
  end
end
```


in config
```
config :my_app, MyApp.Clickhouse,
  connection_urls: System.get_env("CLICKHOUSE_URLS")
```


```export CLICKHOUSE_URLS= "http://yandex-clickhouse-server:8123/my_app_db"```

**Comment by antonovga** [comment]
Thank you for your response, my problem was in particular old phoenix project, tried in new one - everything works as expected.

**Comment by alex88** [comment]
Does this work for you @antonovga? I'm getting this exception
```
** (CompileError) lib/myapp/clickhouse.ex:5: undefined function get_connection_strings/0 (there is no such import)
```

Before [this](https://github.com/balance-platform/pillar/commit/85f4e78fe0e7437d7f9f435a75d3452e5170c813) change it was working fine, now I think the `bind_quoted` flag created the problem

**Comment by alex88** [comment]
Yeah I'm trying to see if bind_quotes can be removed so that the options are unquoted at runtime

**Comment by sofakingworld** [comment]
@alex88 provide please your current code for connection, i'll try help you

**Comment by alex88** [comment]
@sofakingworld 

```elixir
defmodule MyApp.Clickhouse do
  require Logger

  use Pillar,
    connection_strings: [Confex.get_env(:myapp, __MODULE__) |> Keyword.get(:connection_string)],
    name: __MODULE__,
    pool_size: Confex.get_env(:myapp, __MODULE__) |> Keyword.get(:pool_size)
```

my config

```elixir
config :myapp, MyApp.Clickhouse,
  connection_string: {:system, "CLICKHOUSE_URL", "http://localhost:8123/myapp"},
  pool_size: 30
```

I've inspected the poolboy PID state and indeed the connection url used is the fallback one instead of the one injected at runtime

**Comment by sofakingworld** [comment]
Did you try trick with [connection_string](https://github.com/balance-platform/pillar/issues/47#issuecomment-1215269517) function?

```
  def connections_list do
    urls = Application.fetch_env!(:my_app, MyApp.Clickhouse)[:connection_urls]
    String.split(urls, ",")
  end
  ```
  
  It's executed on start of Pool. 
  
  `Confex.get_env(:myapp, __MODULE__) |> Keyword.get(:connection_string)` is "baked" in compile time.
  
  Confex is run-time configuration tool, but in elixir, code, that is outside of function - executes in compile time.

**Comment by sofakingworld** [comment]
in other words: put `[Confex.get_env(:myapp, __MODULE__) |> Keyword.get(:connection_string)]` in function and pmacroass it as argument to `use Pillar`

hope this help you)

**Comment by alex88** [comment]
@sofakingworld that's the version that returns
```
** (CompileError) lib/myapp/clickhouse.ex:5: undefined function get_connection_strings/0 (there is no such import)
```

**Comment by alex88** [comment]
Just to give you the full code
```elixir
defmodule MyApp.Clickhouse do
  require Logger

  use Pillar,
    connection_strings: connection_strings(),
    name: __MODULE__,
    pool_size: 20

  def connection_strings() do
    [Confex.get_env(:myapp, __MODULE__) |> Keyword.get(:connection_string)]
  end
```

**Comment by sofakingworld** [comment]
I reproduced this bug, in couple days i'll fix it and release new version

**Comment by alex88** [comment]
> I reproduced this bug, in couple days i'll fix it and release new version

Thanks a lot! I think `bind_quoted` created the issue but I'm not very familiar with metaprogramming

**Comment by sofakingworld** [comment]
@alex88 sorry, i lied about couple days ;)

Would you check please https://github.com/balance-platform/pillar/tree/bind-quoted-detox? 

In my test project it worked

**Comment by alex88** [comment]
@sofakingworld that works, thanks you so much!

**Comment by sofakingworld** [comment]
Fine, thanks for feedback)

**Comment by sofakingworld** [comment]
Version 0.31.0 released
