### ISSUE TITLE
Test Sandbox envioremente like Ecto

### ISSUE THREAD

**Issue by RodolfoSilva** [balance-platform/pillar#71]
Does have any plans to implement a Sandbox to be used in the test environment like Ecto does?

**Comment by sofakingworld** [comment]
Ecto Sandbox is based on transactions https://hexdocs.pm/ecto_sql/Ecto.Adapters.SQL.Sandbox.html

Clickhouse doesn't support classical BEGIN TRANSACTION and COMMIT/ROLLBACK

Thats why there are no such plans

**Comment by sofakingworld** [comment]
We do clean up table before every test

```
    setup do
      Clickhouse.query("TRUNCATE TABLE events")

      {:ok, %{}}
    end
```

**Comment by sofakingworld** [comment]
And another strategy:

1. generate uniq ID 
2. Insert into clickhouse some records with uniq id
3. select from clickhouse, where id == our_uniq_id

**Comment by RodolfoSilva** [comment]
Thanks @sofakingworld :D
